---
- name: "Subscription Manifest"
  include_role: theforeman.foreman.manifest
  vars:
    manifest_path: "{{ manifest_path | default(~/manifest.zip) }}"
    manifest_download: "{{ manifest_download | default(False) }}"
    rhsm_username: "{{ rhsm_username | default(omit) }}"
    rhsm_password: "{{ rhsm_password | default(omit) }}"
    manifest_uuid: "{{ manifest_uuid | default(omit) }}"

- name: "Enable rhel-7-server-rpms"
  include_role: theforeman.foreman.repositories
  vars:
    products:
      - name: Red Hat Enterprise Linux Server
        repository_sets:
          - name: Red Hat Enterprise Linux 7 Server (RPMs)
            basearch: x86_64
            releasever: 7Server

- name: "Create Sync Plan"
  include_role: theforeman.foreman.sync_plans
  vars:
    sync_plans:
      - name: "{{ sync_plan_name | default('RHEL Sync Plan') }}"
        interval: "{{ sync_plan_interval | default(daily) }}"
        cron_expression: "{{ sync_plan_cron_expression | default(omit) }}"
        sync_plan_sync_date: "{{ sync_plan_sync_date | default(2020-01-01 00:00:00 UTC) }}"
        products:
          - Red Hat Enterprise Linux Server

- name: "Create Activation Key"
  include_role: theforeman.foreman.activation_keys
  vars:
    activation_keys:
      - name: "{{ activation_key_name }}"
        description: "Generated by ansible role theforeman.foreman.basic_setup_rhel7"
